<?php

require '/var/www/token.php';
define('X_API_KEY_TOKEN', BILLIONAIRE1_TOKEN);
define('FACEBOOK_APP_TOKEN', BILLIONAIRE1_FACEBOOK_TOKEN);
define('FACEBOOK_APP_TOKEN_DEV', BILLIONAIRE1_FACEBOOK_TOKEN_DEV);
